#since the env.rb file is autogenerated, I'm adding my own stuff here.

require 'rspec' #for page.shoud etc
require 'capybara/cucumber'
require 'capybara/poltergeist'
require 'pry'
require 'capybara-screenshot'
require 'capybara-screenshot/cucumber'
require 'firefox'

#@driver_name = ENV['DRIVER'] || "poltergeist"
#Capybara.javascript_driver = @driver_name.to_sym
#Capybara.app_host = ENV['HOST'] || "http://x:x"
