#since the env.rb file is autogenerated, I'm adding my own stuff here.

#@driver_name = ENV['DRIVER'] || "poltergeist"
#Capybara.javascript_driver = @driver_name.to_sym
#Capybara.app_host = ENV['HOST'] || "http://x:x"

require 'rspec' #for page.shoud etc
require 'capybara/cucumber'
require 'capybara/poltergeist'
require 'pry'
require 'capybara-screenshot'
require 'capybara-screenshot/cucumber'
require 'firefox'

Capybara.register_driver :chrome do |app|
  Capybara::Selenium::Driver.new(app, :browser => :chrome)
end

#Capybara.current_driver = :selenium
#Capybara.javascript_driver = :selenium
Capybara.default_max_wait_time = 10
